[package]
name = "resolver"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true

[dependencies]
sq-3-parser = { path = "../parser" }
string_literals = { path = "../string_literals" }
db = { path = "../db" }
la-arena = "0.3.1"
walkdir = "2"
phf = { workspace = true }
rustc-hash = { workspace = true }
salsa = { workspace = true }
line-index = { workspace = true }
bitflags = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
